version: '3.8'
services:
  back-java:
    build: backend/.
    volumes:
      - ./backend/app/.:/usr/src/app
    ports:
      - 8080:8080
    working_dir: /usr/src/app/soap-services-shopping
    command: sh -c "mvn clean install && mvn exec:java"
    # command: sh -c "mvn package"
  front-vue:
    build: ./frontend/.
    volumes:
      - ./frontend/app/.:/usr/src/app
    ports:
      - 3000:5173
    working_dir: /usr/src/app/vue-app-shopping
    command: sh -c "npm run dev"
